version: '3'
services:
  app1:
    build:
      context: ./app1
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app1:/app
    depends_on:
      - app2

  app2:
    build:
      context: ./app2
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app2:/app
